# Generated by Django 3.2.4 on 2021-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAndProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc', models.CharField(blank=True, max_length=255, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('TaxPer', models.FloatField(blank=True, null=True)),
                ('TaxType', models.FloatField(blank=True, null=True)),
                ('TaxAmount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
